### ISSUE TITLE
Special chars in resources

### ISSUE THREAD

**Issue by UngureanuI2000** [davidhorak/es-resx-to-js#1]
Hi,
I have a problem with using special characters in the resx file (in my case is apostrophe).
I suggest you replace the 65 line in the index.js from: 
keypairs += '\t' + name + ': \'' + value + '\',\n';
to:
keypairs +="\t" + JSON.stringify(name)+":"+JSON.stringify(value) +",\n";

Thank you
Regards

**Comment by davidhorak** [comment]
Hi there,
It has been fixed in the latest commit. 

Thanks for pointing that out.

David
